version: '3'
services:
  druid-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      - DRUID_HOME=/home/ubuntu/apache-druid-27.0.0
      - PATH=$JAVA_HOME/bin:$DRUID_HOME/bin:$PATH
      - PATH=$PATH:$HOME/bin
    ports:
      - "8888:8888"
    command: bash -c "/apache-druid-27.0.0/bin/start-druid"
    networks:
      - mi-red
networks:
  mi-red:
    external: true      
